/* SAMSARA - Disclaimers & Legal Components */
import { useState } from 'react';
import T from '../utils/tokens';
import S from '../utils/styles';

/* ── DisclaimerGate: one-time acceptance on first use ─────────────────── */
export function DisclaimerGate({ onAccept }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 600, background: T.bg,
      display: 'flex', flexDirection: 'column', alignItems: 'center',
      justifyContent: 'center', padding: 20,
    }}>
      <div style={{
        maxWidth: 420, width: '100%', animation: 'fadeUp .4s ease both',
      }}>
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <div style={{ fontSize: 28, marginBottom: 12, opacity: 0.4 }}>{'\u2695'}</div>
          <h2 style={{
            fontFamily: T.fd, fontSize: 24, fontWeight: 300, color: T.t1, marginBottom: 8,
          }}>Important Information</h2>
        </div>

        <div style={{
          ...S.card, padding: '16px', marginBottom: 16,
          borderColor: T.border, background: 'rgba(255,255,255,0.02)',
        }}>
          <p style={{ fontSize: 12, color: T.t2, fontFamily: T.fm, lineHeight: 1.7, marginBottom: 12 }}>
            Samsara is a <strong style={{ color: T.t1 }}>calculation and logging tool</strong> for tracking injectable medication protocols prescribed by your healthcare provider.
          </p>
          <p style={{ fontSize: 12, color: T.t2, fontFamily: T.fm, lineHeight: 1.7, marginBottom: 12 }}>
            This app does <strong style={{ color: T.t1 }}>not</strong> provide medical advice, diagnoses, or treatment recommendations. All dosing, compound selection, and protocol decisions should be made in consultation with a licensed healthcare professional.
          </p>
          <p style={{ fontSize: 12, color: T.t2, fontFamily: T.fm, lineHeight: 1.7 }}>
            AI-generated body composition estimates are <strong style={{ color: T.t1 }}>approximations for informational purposes only</strong> and should not be used for medical decisions.
          </p>
        </div>

        {/* Expandable full terms */}
        <button onClick={() => setExpanded(!expanded)} style={{
          background: 'none', border: 'none', color: T.t3, fontFamily: T.fm,
          fontSize: 11, cursor: 'pointer', padding: '4px 0', width: '100%',
          textAlign: 'center', marginBottom: expanded ? 12 : 16,
        }}>{expanded ? '\u25BC' : '\u25B6'} Full Terms</button>

        {expanded && (
          <div style={{
            padding: '12px 14px', borderRadius: 8, marginBottom: 16,
            background: 'rgba(255,255,255,0.02)', border: '1px solid ' + T.border,
            maxHeight: 200, overflowY: 'auto',
          }}>
            <p style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, lineHeight: 1.7, marginBottom: 8 }}>
              <strong style={{ color: T.t2 }}>No Medical Advice.</strong> Samsara and its developers are not licensed medical professionals. The information provided by this application, including but not limited to dosage calculations, compound information, and AI-generated analysis, is for informational and educational purposes only. Nothing in this app constitutes medical advice, diagnosis, or treatment.
            </p>
            <p style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, lineHeight: 1.7, marginBottom: 8 }}>
              <strong style={{ color: T.t2 }}>Consult Your Physician.</strong> Always seek the advice of your physician or other qualified healthcare provider with any questions you may have regarding a medical condition, medication, or treatment protocol. Never disregard professional medical advice or delay seeking it because of information provided by this application.
            </p>
            <p style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, lineHeight: 1.7, marginBottom: 8 }}>
              <strong style={{ color: T.t2 }}>Accuracy Disclaimer.</strong> While Samsara strives for accuracy in its calculations, the app is provided "as is" without warranty of any kind. Users are responsible for verifying all calculations and dosages with their prescribing physician before administration.
            </p>
            <p style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, lineHeight: 1.7, marginBottom: 8 }}>
              <strong style={{ color: T.t2 }}>AI Analysis Limitations.</strong> Body composition estimates generated by artificial intelligence are approximations based on visual analysis. They are not equivalent to clinical body composition measurements (DEXA, BIA, hydrostatic weighing) and should not be relied upon for medical or diagnostic purposes.
            </p>
            <p style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, lineHeight: 1.7, marginBottom: 8 }}>
              <strong style={{ color: T.t2 }}>Photo Privacy.</strong> Photos submitted for AI analysis are transmitted securely, processed for the sole purpose of generating body composition estimates, and are not stored on any server after processing. Photos are stored locally on your device only.
            </p>
            <p style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, lineHeight: 1.7 }}>
              <strong style={{ color: T.t2 }}>Assumption of Risk.</strong> By using this application, you acknowledge that you are using it at your own risk. The developers of Samsara shall not be liable for any adverse effects, injury, or damages resulting from the use of information provided by this application.
            </p>
          </div>
        )}

        <button onClick={onAccept} style={{
          ...S.logBtn, width: '100%', padding: '16px', textAlign: 'center',
          fontSize: 14, fontWeight: 700, letterSpacing: 0.5,
          background: T.gold, color: T.bg, border: 'none', borderRadius: 10,
        }}>I Understand — Continue</button>

        <p style={{
          fontSize: 9, color: T.t3, fontFamily: T.fm, textAlign: 'center',
          marginTop: 12, lineHeight: 1.5, opacity: 0.6,
        }}>By continuing, you acknowledge that this app is not a substitute for professional medical advice.</p>
      </div>
    </div>
  );
}

/* ── CalcDisclaimer: persistent small footer on calculator ─────────────── */
export function CalcDisclaimer() {
  return (
    <p style={{
      fontSize: 10, color: T.t3, fontFamily: T.fb, fontWeight: 400, textAlign: 'center',
      lineHeight: 1.55, padding: '12px 16px', opacity: 0.6, letterSpacing: 0.1,
    }}>
      Verify all calculations with your prescribing physician before administration.
      This tool does not constitute medical advice.
    </p>
  );
}

/* ── AIDisclaimer: shown before AI analysis ─────────────── */
export function AIDisclaimer({ onProceed, onCancel }) {
  const [consent, setConsent] = useState(false);

  return (
    <div style={{
      ...S.card, padding: '16px', marginBottom: 16,
      borderColor: 'rgba(255,180,50,0.25)', background: 'rgba(255,180,50,0.04)',
    }}>
      <div style={{ fontSize: 12, fontWeight: 600, color: T.t1, fontFamily: T.fb, marginBottom: 8 }}>
        {'\u2139'} Before You Analyze
      </div>
      <p style={{ fontSize: 11, color: T.t2, fontFamily: T.fm, lineHeight: 1.6, marginBottom: 10 }}>
        Your photo will be sent to a secure AI service for body composition estimation.
        Results are <strong style={{ color: T.t1 }}>approximations</strong>, not clinical measurements.
      </p>

      <button onClick={() => setConsent(!consent)} style={{
        display: 'flex', alignItems: 'center', gap: 8,
        background: 'none', border: 'none', cursor: 'pointer',
        padding: '6px 0', width: '100%',
      }}>
        <div style={{
          width: 16, height: 16, borderRadius: 3, flexShrink: 0,
          border: '1.5px solid ' + (consent ? T.gold : T.t3),
          background: consent ? T.goldS : 'transparent',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
        }}>
          {consent && <span style={{ color: T.gold, fontSize: 11 }}>{'\u2713'}</span>}
        </div>
        <span style={{ fontSize: 11, color: T.t2, fontFamily: T.fm, textAlign: 'left' }}>
          I understand this is not a medical assessment
        </span>
      </button>

      <div style={{ height: 4 }} />

      {/* What gets sent */}
      <details style={{ marginBottom: 10 }}>
        <summary style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, cursor: 'pointer' }}>What data is sent?</summary>
        <div style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, lineHeight: 1.6, padding: '6px 0 0 12px' }}>
          {[
            'Your uploaded photo(s)',
            'Current weight and waist measurement',
            'Compound names and dosages from your stack',
            'Your stated goal (e.g., fat loss, recomp)',
          ].map((item, i) => (
            <div key={i}>{'\u2022'} {item}</div>
          ))}
          <div style={{ marginTop: 4, color: T.t3 }}>Photos are processed and not stored on any server.</div>
        </div>
      </details>

      <div style={{ display: 'flex', gap: 8 }}>
        <button onClick={onCancel} style={{ ...S.newVialBtn, flex: 1 }}>Cancel</button>
        <button onClick={onProceed} disabled={!consent} style={{
          ...S.logBtn, flex: 2, padding: '10px', textAlign: 'center',
          opacity: consent ? 1 : 0.4, cursor: consent ? 'pointer' : 'default',
        }}>Continue to Analysis</button>
      </div>
    </div>
  );
}

/* ── AboutDisclaimer: full legal text for Settings/About ─────────────── */
export function AboutDisclaimer() {
  return (
    <div style={{
      padding: '12px 14px', borderRadius: 8,
      background: 'rgba(255,255,255,0.02)', border: '1px solid ' + T.border,
    }}>
      <div style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 8 }}>Legal</div>
      <p style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, lineHeight: 1.7, marginBottom: 6 }}>
        Samsara is a calculation and logging tool for educational and informational purposes.
        It is not a medical device and does not provide medical advice, diagnoses, or treatment recommendations.
      </p>
      <p style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, lineHeight: 1.7, marginBottom: 6 }}>
        All compound information is sourced from publicly available research literature and is provided for educational reference only.
        Inclusion of a compound does not constitute an endorsement or recommendation for use.
      </p>
      <p style={{ fontSize: 10, color: T.t3, fontFamily: T.fm, lineHeight: 1.7 }}>
        Always consult a licensed healthcare provider before starting, modifying, or discontinuing any medication or treatment protocol.
      </p>
    </div>
  );
}
