import T from './tokens';

/* Golden ratio spacing scale: 4, 8, 13, 21, 34, 55 */

const S = {
  root: { minHeight: '100vh', background: T.bg, color: T.t1, fontFamily: T.fb, maxWidth: 480, margin: '0 auto', position: 'relative', overflow: 'hidden' },
  bgGlow: { position: 'fixed', top: -120, left: '50%', transform: 'translateX(-50%)', width: 500, height: 500, borderRadius: '50%', pointerEvents: 'none', background: 'radial-gradient(circle,rgba(201,168,76,0.03) 0%,transparent 70%)', zIndex: 0 },
  content: { position: 'relative', zIndex: 1, padding: '13px 13px 90px', overflowY: 'auto', height: '100vh' },
  header: { textAlign: 'center', marginBottom: 21 },
  brand: { fontFamily: T.fd, fontSize: 26, fontWeight: 300, letterSpacing: 8, color: T.t1, margin: 0, marginTop: -4 },
  sub: { fontFamily: T.fm, fontSize: 11, letterSpacing: 3, color: T.t3, textTransform: 'uppercase', marginTop: 4 },
  pills: { display: 'flex', flexWrap: 'wrap', gap: 8, justifyContent: 'center', marginBottom: 21 },
  pill: { background: 'transparent', border: `1px solid ${T.border}`, borderRadius: 21, padding: '8px 13px', fontSize: 13, color: T.t2, cursor: 'pointer', fontFamily: T.fm, letterSpacing: 0.5, transition: 'all .15s ease' },
  pillOn: { background: T.goldS, borderColor: T.goldM, color: T.gold },
  card: { background: T.card, border: `1px solid ${T.border}`, borderRadius: 13, padding: '13px 13px', marginBottom: 13, boxShadow: '0 1px 3px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.04)', transition: 'all .15s ease' },
  field: { marginBottom: 0 },
  label: { display: 'block', fontSize: 11, letterSpacing: 2.5, textTransform: 'uppercase', color: T.t3, marginBottom: 8, fontFamily: T.fm },
  frow: { display: 'flex', alignItems: 'center', gap: 8 },
  input: { flex: 1, background: 'rgba(0,0,0,0.25)', border: `1px solid ${T.border}`, borderRadius: 8, padding: '13px 13px', fontSize: 17, fontWeight: 600, color: T.t1, fontFamily: T.fm, outline: 'none', transition: 'border-color .2s', WebkitAppearance: 'none', boxShadow: 'inset 0 1px 3px rgba(0,0,0,0.3)' },
  tag: { background: 'rgba(255,255,255,0.03)', border: `1px solid ${T.border}`, borderRadius: 8, padding: '13px 13px', fontSize: 12, color: T.t3, fontWeight: 600, fontFamily: T.fm, minWidth: 42, textAlign: 'center' },
  divider: { height: 1, background: T.border, margin: '13px 0' },
  dividerGold: { height: 1, background: `linear-gradient(90deg,transparent,${T.goldM},transparent)`, margin: '13px 0' },
  lockBtn: { background: 'transparent', border: `1px solid ${T.border}`, borderRadius: 8, padding: '8px 13px', fontSize: 12, color: T.t3, cursor: 'pointer', fontFamily: T.fm, letterSpacing: 0.5, transition: 'all .15s ease', whiteSpace: 'nowrap' },
  lockOn: { borderColor: T.goldM, color: T.gold, background: T.goldS },
  togGrp: { display: 'flex', borderRadius: 8, overflow: 'hidden', border: `1px solid ${T.border}` },
  togBtn: { background: 'rgba(255,255,255,0.02)', border: 'none', padding: '13px 13px', fontSize: 12, color: T.t3, cursor: 'pointer', fontFamily: T.fm, fontWeight: 600, transition: 'all .15s ease' },
  togOn: { background: T.goldS, color: T.gold },
  freqBtn: { flex: 1, background: 'rgba(255,255,255,0.02)', border: `1px solid ${T.border}`, borderRadius: 8, padding: '8px 4px', fontSize: 12, color: T.t3, cursor: 'pointer', fontFamily: T.fm, fontWeight: 500, transition: 'all .15s ease', textAlign: 'center' },
  freqOn: { background: T.goldS, borderColor: T.goldM, color: T.gold },
  resultCard: { background: 'rgba(201,168,76,0.025)', border: '1px solid rgba(201,168,76,0.1)', borderRadius: 13, padding: '13px 13px', marginBottom: 13, boxShadow: '0 1px 3px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.04)' },
  resRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  resLabel: { fontSize: 11, letterSpacing: 2.5, textTransform: 'uppercase', color: T.t3, fontFamily: T.fm },
  resGold: { fontSize: 14, fontWeight: 700, color: T.gold, fontFamily: T.fm },
  drawLabel: { display: 'block', fontSize: 11, letterSpacing: 3, textTransform: 'uppercase', color: T.t3, fontFamily: T.fm, marginBottom: 4 },
  drawVal: { display: 'block', fontSize: 40, fontWeight: 300, color: T.t1, fontFamily: T.fd, lineHeight: 1.1 },
  drawUnit: { fontSize: 15, fontWeight: 600, color: T.goldM },
  drawSub: { display: 'block', fontSize: 12, color: T.t3, marginTop: 4, fontFamily: T.fm },
  stats: { display: 'flex', justifyContent: 'space-around', paddingTop: 8 },
  stat: { textAlign: 'center' },
  statV: { display: 'block', fontSize: 17, fontWeight: 700, color: T.t1, fontFamily: T.fm },
  statL: { display: 'block', fontSize: 10, letterSpacing: 1.5, textTransform: 'uppercase', color: T.t3, marginTop: 4, fontFamily: T.fm },
  warning: { marginTop: 8, padding: '8px 13px', background: T.warn, border: `1px solid ${T.warnB}`, borderRadius: 8, fontSize: 13, color: T.warnT, lineHeight: 1.6, fontFamily: T.fb },
  infoBox: { marginTop: 8, padding: '8px 13px', background: 'rgba(201,168,76,0.05)', border: '1px solid rgba(201,168,76,0.12)', borderRadius: 8, fontSize: 13, color: 'rgba(201,168,76,0.7)', lineHeight: 1.6, fontFamily: T.fb },
  trackRow: { display: 'flex', alignItems: 'center', gap: 13, padding: '13px', background: T.card, border: `1px solid ${T.border}`, borderRadius: 13, marginBottom: 8, transition: 'all .15s ease', cursor: 'pointer', boxShadow: '0 1px 3px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.04)' },
  trackName: { fontSize: 14, fontWeight: 600, color: T.t1, fontFamily: T.fb, letterSpacing: 0.5 },
  trackMeta: { fontSize: 11, color: T.t3, marginTop: 4, fontFamily: T.fm, letterSpacing: 2.5, textTransform: 'uppercase' },
  logBtn: { background: T.goldS, border: `1px solid ${T.goldM}`, borderRadius: 8, padding: '8px 13px', fontSize: 13, fontWeight: 600, color: T.gold, cursor: 'pointer', fontFamily: T.fm, letterSpacing: 0.5, transition: 'all .15s ease', whiteSpace: 'nowrap' },
  loggedBadge: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4 },
  vialCard: { background: T.card, border: `1px solid ${T.border}`, borderRadius: 13, padding: '13px', marginBottom: 13, boxShadow: '0 1px 3px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.04)' },
  vialHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  vialName: { fontSize: 14, fontWeight: 600, color: T.t1, fontFamily: T.fb },
  vialConc: { fontSize: 13, color: T.gold, fontFamily: T.fm },
  barTrack: { height: 4, background: 'rgba(255,255,255,0.05)', borderRadius: 2, overflow: 'hidden', marginBottom: 8 },
  barFill: { height: '100%', borderRadius: 2, transition: 'width .5s ease' },
  vialStats: { display: 'flex', justifyContent: 'space-between', fontSize: 11, color: T.t3, fontFamily: T.fm, letterSpacing: 0.5, marginBottom: 8 },
  newVialBtn: { width: '100%', background: 'transparent', border: `1px solid ${T.border}`, borderRadius: 8, padding: '8px', fontSize: 13, color: T.t3, cursor: 'pointer', fontFamily: T.fm, letterSpacing: 0.5, transition: 'all .15s ease' },
  logDate: { fontSize: 11, fontWeight: 600, color: T.gold, fontFamily: T.fm, letterSpacing: 2.5, marginBottom: 8, textTransform: 'uppercase' },
  logRow: { display: 'flex', alignItems: 'center', gap: 8, padding: '8px 13px', background: T.card, border: `1px solid ${T.border}`, borderRadius: 8, marginBottom: 4, boxShadow: '0 1px 3px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.04)' },
  logName: { flex: 1, fontSize: 14, fontWeight: 500, color: T.t1, fontFamily: T.fb },
  logDose: { fontSize: 13, color: T.t2, fontFamily: T.fm },
  logTime: { fontSize: 11, color: T.t3, fontFamily: T.fm, minWidth: 52, textAlign: 'right' },
  segWrap: { display: 'flex', gap: 2, background: 'rgba(0,0,0,0.3)', borderRadius: 8, padding: 4, marginBottom: 21, border: `1px solid ${T.border}` },
  segBtn: { flex: 1, background: 'transparent', border: 'none', borderRadius: 8, padding: '8px 0', fontSize: 13, fontWeight: 500, color: T.t3, cursor: 'pointer', fontFamily: T.fm, transition: 'all .15s ease' },
  segOn: { background: T.goldS, color: T.gold },
  tabBar: { position: 'fixed', bottom: 0, left: '50%', transform: 'translateX(-50%)', width: '100%', maxWidth: 480, display: 'flex', justifyContent: 'space-around', alignItems: 'center', background: 'rgba(8,9,11,0.88)', backdropFilter: 'blur(40px)', WebkitBackdropFilter: 'blur(40px)', borderTop: `1px solid ${T.border}`, padding: '8px 0 env(safe-area-inset-bottom, 8px)', zIndex: 100 },
  tabBtn: { background: 'none', border: 'none', cursor: 'pointer', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, padding: '4px 8px', position: 'relative' },
  tabLabel: { fontSize: 10, fontWeight: 400, letterSpacing: 1, fontFamily: T.fm, transition: 'color .2s' },
  tabLine: { position: 'absolute', bottom: 0, left: '50%', transform: 'translateX(-50%)', width: 16, height: 2, borderRadius: 1, background: T.amberFull },
  tabDot: { position: 'absolute', bottom: 2, left: '50%', transform: 'translateX(-50%)', width: 3, height: 3, borderRadius: '50%', background: T.amberFull },
  libStat: { background: 'rgba(0,0,0,0.2)', borderRadius: 8, padding: '8px 13px' },
  libStatL: { display: 'block', fontSize: 10, letterSpacing: 2.5, textTransform: 'uppercase', color: T.t3, fontFamily: T.fm, marginBottom: 4 },
  libStatV: { display: 'block', fontSize: 14, fontWeight: 600, color: T.t1, fontFamily: T.fm },
};

export default S;
